# Generated by Django 3.0.3 on 2020-03-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_friend'),
        ('notecards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecards',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
            preserve_default=False,
        ),
    ]
