# Generated by Django 3.0.3 on 2020-03-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0002_notecards_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecards',
            name='owner',
        ),
    ]
